services:
  cypress:
    image: node:22 
    container_name: cypress
    working_dir: /e2e
    command: /bin/sh -c "npm install"
    volumes:
      - .:/e2e
    environment:
      SUITE: loginUserSuite
      BROWSER: chrome
    networks:
      - project-network

networks:
  project-network:
    external: true
