services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.jenkins
    image: jenkins_project
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: 
      ["/bin/bash", "-c", "/var/jenkins_home/setup-ssh.sh || echo 'SSH setup failed, continuing...' && /usr/bin/tini -- /usr/local/bin/jenkins.sh"]
    depends_on:
      - sonarqube
    environment:
      #BUILD_URL: 'http://localhost:8080/'
      SONAR_PROYECT_KEY: "YourStoreSite"
    networks:
      - project-network


  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonar-scanner
    depends_on:
      - sonarqube
      - cypress
    networks:
      - project-network
    volumes:
      - jenkins_home:/var/jenkins_home
      - node-bin:/usr/local/bin      
    environment:
      SONAR_HOST_URL: "http://sonarqube:9000"

  cypress:
    image: cypress/included:13.7.1
    container_name: cypress
    working_dir: /e2e
    volumes:
      - node-bin:/usr/local/bin 
      - ./tests:/e2e
      - ./cypress-reports:/e2e/cypress/reports
    networks:
      - project-network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - project-network

  postgres:
    image: postgres:13.7  
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

volumes:
  jenkins_home:
    name: jenkins_home
  sonarqube_data:
    name: sonarqube_data
  sonarqube_logs:
    name: sonarqube_logs
  sonarqube_extensions:
    name: sonarqube_extensions
  postgres_data:
    name: postgres_data
  node-bin:
    name: node-bin

networks:
  project-network:
    name: project-network
    driver: bridge