services:
  cypress:
    image: cypress/included:13.7.1
    restart: "no"
    container_name: cypress
    working_dir: /e2e
    environment:
      SUITE: loginUserSuite
      BROWSER: chrome
    command:
      - "/bin/sh"
      - "-c"
      - "npm install"
    volumes:
      - .:/e2e
    networks:
      - project-network

networks:
  project-network:
    external: true
